---
# tasks file for proxy_settings

- name: Configure proxy settings for OS (/etc/environment)
  blockinfile:
    dest: /etc/environment
    create: yes
    block: |
      {% if proxy_settings_http_proxy is defined %}
      http_proxy="{{ proxy_settings_http_proxy }}"
      HTTP_PROXY="{{ proxy_settings_http_proxy }}"
      {% endif %}
      {% if proxy_settings_ftp_proxy is defined %}
      ftp_proxy="{{ proxy_settings_ftp_proxy }}"
      FTP_PROXY="{{ proxy_settings_ftp_proxy }}"
      {% endif %}
      {% if proxy_settings_https_proxy is defined %}
      https_proxy="{{ proxy_settings_https_proxy }}"
      HTTPS_PROXY="{{ proxy_settings_https_proxy }}"
      {% endif %}
      {% if proxy_settings_no_proxy is defined %}
      no_proxy="{{ proxy_settings_no_proxy }}"
      NO_PROXY="{{ proxy_settings_no_proxy }}"
      {% endif %}
  tags: proxy

- name: Configure proxy settings for OS (/etc/profile.d/proxy.sh)
  template:
    src: proxy.sh.j2
    dest: /etc/profile.d/proxy.sh
  tags: proxy

- name: Check if wgetrc exists
  stat:
    path: /etc/wgetrc
  register: wgetrc
  tags: proxy

- name: Add proxy settings to wgetrc (if exists)
  blockinfile:
    dest: /etc/wgetrc
    block: |
      use_proxy = on
      http_proxy = {{ proxy_settings_http_proxy }}
      https_proxy = {{ proxy_settings_https_proxy }}
      ftp_proxy = {{ proxy_settings_ftp_proxy }}
      no_proxy = {{ proxy_settings_no_proxy }}
  when: wgetrc.stat.exists
  tags: proxy

- name: Configure proxy settings for dnf
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: '^proxy='
    line: "proxy={{ proxy_settings_yum_proxy }}"
  tags: proxy
  when: ansible_pkg_mgr == 'dnf' and proxy_settings_yum_proxy is defined

- name: Configure proxy_username for dnf
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: '^proxy_username='
    line: "proxy_username={{ proxy_settings_yum_proxy_username }}"
  tags: proxy
  when: ansible_pkg_mgr == 'dnf' and proxy_settings_yum_proxy_username is defined

- name: Configure proxy_password for dnf
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: '^proxy_password='
    line: "proxy_password={{ proxy_settings_yum_proxy_password }}"
  tags: proxy
  when: ansible_pkg_mgr == 'dnf' and proxy_settings_yum_proxy_password is defined

- name: Configure proxy settings for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy='
    line: "proxy={{ proxy_settings_yum_proxy }}"
  tags: proxy
  when: ansible_pkg_mgr == 'yum' and proxy_settings_yum_proxy is defined

- name: Configure proxy_username for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy_username='
    line: "proxy_username={{ proxy_settings_yum_proxy_username }}"
  tags: proxy
  when: ansible_pkg_mgr == 'yum' and proxy_settings_yum_proxy_username is defined

- name: Configure proxy_password for yum
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy_password='
    line: "proxy_password={{ proxy_settings_yum_proxy_password }}"
  tags: proxy
  when: ansible_pkg_mgr == 'yum' and proxy_settings_yum_proxy_password is defined

- name: Configure proxy settings for apt-get/aptitude
  template:
    src: 80proxy.j2
    dest: /etc/apt/apt.conf.d/80proxy
  tags: proxy
  when: ansible_pkg_mgr == 'apt'

- name: Configure proxy settings for Suse
  template:
    src: proxy.j2
    dest: /etc/sysconfig/proxy
  tags: proxy
  when: ansible_pkg_mgr == 'zypper'
